### ISSUE TITLE
The math definition of Value function

### ISSUE THREAD

**Issue by stevenmailca** [011235813/discrete_mean_field_game#2]
Hi Jiachen,

Sorry for disturbing. In your paper/Appendix B-Algorithms/Algorithm 2, there's V(pi_n+1; w)-V(pi_n; w) which corresponds your below code: # TD error = r + gamma * v(s'; w) - v(s; w); delta = reward + discount*(vec_features_next.dot(ac.w)) - (vec_features.dot(ac.w))
May I ask what's the math definition of Value function? I don't find the specific math definition of the Value function, but only see the definition of Value function in your code as discount*(vec_features_next.dot(ac.w)). Is there some reference or math formula can help me to understand V(s, w)=discount*(vec_features_next.dot(ac.w))?   
Thank you very much in advance!

**Comment by 011235813** [comment]
It's defined according to the standard definition of a value function (with respect to some policy) in an MDP (Sutton & Barto's book 2018), namely V(s) = E_{\pi}[ \sum_t \gamma^t R(s_t,a_t) | s_0 = s] (using the RL notation with s for state and a for action).
In Algorithm 2, the policy is parameterized by \theta, and lines 9-10 conduct the standard TD learning update to estimate the value function from transition tuples experienced under the current policy.

**Comment by stevenmailca** [comment]
Hi Jiachen,
Thank you very much for sharing the knowledge and giving the kind explanation!

**Comment by stevenmailca** [comment]
Hi Jiachen,

So sorry for disturbing.  May I kindly ask is self.mat_alpha = np.log( 1 + np.exp( self.theta * (temp - self.shift))) equivalent to self.mat_alpha = self.theta * (temp - self.shift) ? Thank you very much in advance!

**Comment by 011235813** [comment]
Not in general.

**Comment by stevenmailca** [comment]
> Not in general.

Thank you, Jiachen. Yes, you're right, only for large positive case they are equivalent and within [-1, 1] softplus gives continuous derivative.

**Comment by stevenmailca** [comment]
Hi Jiachen, sorry for disturbing. It seems that the log likelihood log(F)
has multiple local maxima in terms of theta.
Below test results show one local maxima between theta=9 and 10 and another
between theta=12 and 13. Is there a way to determine the global maxima of
log(F)(theta)? Thank you very much in advance!
Initial theta  Exiting train at episode 2000 with theta
5 5.002481
7 7.000529
9 9.15272365
10 9.8571062
11 11.402721
12 12.150159
13 12.87025287
